export const game = [
    ['MALDIVES', 'FACEMASK', 'CANDY', 'JAGUAR', 'CHINA', 'CAMERA', 'KETCHUP', 'EAGLE'],
    ['WOLF',	'BURGER', 'SHOE LACE', 'UKRAINE', 'TIGER', 'TACOS', 'BOOK', 'ITALY'],
    ['MANILA', 'CHAIR', 'ICE CREAM', 'BEAR', 'MEXICO', 'CHARGER', 'BACON', 'SNAKE'],
    ['TOKYO', 'PRINTER', 'DONUT', 'LION', 'SWITZERLAND', 'WALLET', 'FRIED CHICKEN', 'SEAL'],
    ['INDIA', 'COMPUTER', 'MOUSE', 'COFFEE', 'TURTLE', 'NEW YORK CITY',	'WRIST WATCH', 'LASAGNA', 'CHIPANZEE'],
    ['ISRAEL', 'HEADSET', 'PAELLA', 'DOLPHIN', 'ZURICH', 'BAG', 'FRENCH FRIES', 'CAT'],
    ['GERMANY', 'COMPUTER', 'CARBONARA', 'KANGAROO', 'PARIS', 'SPEAKER', 'POPCORN', 'PANDA'],
    ['KOREA', 'KEYBOARD', 'CAKE', 'DOG', 'LONDON', 'PHONE', 'NACHOS', 'FROG'],    
    ['OFFICE', 'BEER', 'EAGLE'],
]